import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = path => readFileSync(resolve(root, path), 'utf8');
const main = 'app/src/main/';
const manifest = read(main + 'AndroidManifest.xml');
assert.deepEqual([...manifest.matchAll(/<uses-permission android:name="([^"]+)"/g)].map(m=>m[1]).sort(), ['android.permission.ACCESS_NETWORK_STATE', 'android.permission.INTERNET']);
assert.match(manifest, /android:allowBackup="false"/);
assert.match(read(main+'res/xml/network_security_config.xml'), /<base-config cleartextTrafficPermitted="false"/);
assert.match(read(main+'res/xml/network_security_config.xml'), /<domain includeSubdomains="false">192\.168\.0\.1<\/domain>/);
const files = [];
function walk(path) { for (const f of readdirSync(resolve(root,path),{withFileTypes:true})) { const p=path+'/'+f.name; if(f.isDirectory()) walk(p); else if(p.endsWith('.java'))files.push(read(p)); } }
walk(main+'java');
const source = files.join('\n');
for (const forbidden of ['bindProcessToNetwork(', 'requestNetwork(', 'WifiNetworkSpecifier', 'new WebView(', 'Log.', 'System.out.', 'READ_MEDIA_IMAGES', 'READ_EXTERNAL_STORAGE', 'WRITE_EXTERNAL_STORAGE', 'BLUETOOTH_CONNECT', 'ACCESS_FINE_LOCATION']) assert.ok(!source.includes(forbidden),forbidden);
const transport=read(main+'java/io/gr3/transfer/CameraTransport.java');
assert.match(transport,/network\.openConnection\(new URL\(allowed\), java\.net\.Proxy\.NO_PROXY\)/);
assert.match(transport,/setRequestMethod\("GET"\)/);
assert.match(transport,/setInstanceFollowRedirects\(false\)/);
assert.match(transport,/setRequestProperty\("Accept-Encoding", "identity"\)/);
assert.ok(!transport.includes('maximum == CameraRules.MAX_JSON_BYTES'));
const saver=read(main+'java/io/gr3/transfer/MediaSaver.java');
assert.match(saver,/IS_PENDING, 1/);assert.match(saver,/IS_PENDING, 0/);
assert.match(saver,/IS_PENDING \+ " = \?", new String\[\]\{"1"\}/);
assert.ok(!saver.includes('Media.EXTERNAL_CONTENT_URI'));
assert.match(read(main+'java/io/gr3/transfer/MainActivity.java'),/setPositiveButton\("确认保存",\(dialog,which\) -> controller\.saveReady\(\)\)/);
const activity=read(main+'java/io/gr3/transfer/MainActivity.java');
assert.match(activity,/if \(resetScroll\) scroll\.scrollTo\(0, 0\);/);
assert.match(activity,/resetScroll \? 0 : scroll\.getScrollY\(\)/);
assert.match(activity,/generation == renderGeneration/);
assert.match(activity,/page\+\+; render\(true\)/);
assert.match(activity,/page--; render\(true\)/);
assert.match(activity,/if \(pages > 1\)/);
assert.match(activity,/button\.setSelected\(active\)/);
assert.match(activity,/setTitle\("更多选项"\)/);
assert.match(activity,/setTitle\("保存 "/);
assert.match(activity,/云备份/);
assert.match(activity,/重启后重新校验并恢复/);
assert.match(activity,/清除应用数据或卸载会删除副本/);
const controller=read(main+'java/io/gr3/transfer/TransferController.java');
assert.match(controller,/context\.getNoBackupFilesDir\(\)/);
assert.match(controller,/recovery\.rememberSave\(entry, id\)/);
assert.match(read(main+'java/io/gr3/transfer/core/StagedOriginals.java'),/LinkOption\.NOFOLLOW_LINKS/);
assert.match(activity,/primary\(bottom,/);
assert.match(activity,/private void entryDetails/);
assert.match(activity,/getConfiguration\(\).fontScale<=1\.15f/);
assert.ok(!activity.includes('entry.status.name()'));
console.log('PASS native source safety audits (static checks, not Android execution)');
